basePath: /
definitions:
  controller.UserReq:
    properties:
      email:
        type: string
    type: object
  models.Product:
    properties:
      brand:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updateAt:
        type: string
      userID:
        type: integer
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      products:
        items:
          $ref: '#/definitions/models.Product'
        type: array
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: farrastimorremboko@gmail.com
    name: API Support
  description: This is a sample for managing user and product
  license:
    name: Apache 2.0
    url: http://www.apache.org/license/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: User and Product API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Get User by Id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get User by Id
swagger: "2.0"
